#Create Dev namespace
apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
  name: dev1
  labels:
    name: dev1

---
apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
  name: test1
  labels:
    name: test1

---
apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
  name: prod1
  labels:
    name: prod1
