#Create resource quota for dev namespace
#kubectl create -f ./resource-quota.yaml --namespace=dev
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-quota-dev
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
#Create resource quota for test namespace
#kubectl create -f ./resource-quota.yaml --namespace=test
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-quota-test
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
#Create resource quota for prod namespace
#kubectl create -f ./resource-quota.yaml --namespace=prod
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-quota-prod
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
