#kubectl create -f ./resource-count.yaml --namespace=dev
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-count
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
